In [324]:
import numpy as np
import math

In [325]:
data = np.array([[-1,0,1],[-.5,.5,1],[0,1,-1],[.5,1,-1],[1,0,1],[1,-1,1],[0,-1,-1],[0,0,-1]])

In [326]:
D_1=np.full(8,1/8)

In [ ]:
X = data[:,:2]
y = data[:,2]
D = np.full(8, 1/8)

y_1 = None

b_error,b_stump = float('inf'),None

for j in range(X.shape[1]):
    features = np.sort(np.unique(X[:,j]))

    thresholds = [(features[k]+ features[k+1])/2 for k in range(len(features)-1)]
    # thresholds = [-.75,-.25,0,.25,.75]
    for t in thresholds:
        preds = np.where(X[:,j] >=t,1,-1)

        incorrect = preds !=y

        error = np.sum(D[incorrect])

        # if error > 0.5:
        #   error = 1 - error
        #   preds = -preds

        if error < b_error:
            b_error = error
            b_stump = (j, t)
            y_1 = preds
        print(j, t,error)
        

print(b_error, b_stump)


at_1 = (1/2)*math.log((1-b_error)/b_error)
at_1

Feature x1, threshold=-0.75, error=0.6250
Feature x1, threshold=-0.25, error=0.7500
Feature x1, threshold=0.25, error=0.3750
Feature x1, threshold=0.75, error=0.2500
Feature x2, threshold=-0.50, error=0.5000
Feature x2, threshold=0.25, error=0.6250
Feature x2, threshold=0.75, error=0.7500
0.25 (0, np.float64(0.75))


0.5493061443340549

In [328]:
y_1

array([-1, -1, -1, -1,  1,  1, -1, -1])

In [329]:
y

array([ 1.,  1., -1., -1.,  1.,  1., -1., -1.])

In [330]:
D*np.exp(-at_1*y*y_1)

array([0.21650635, 0.21650635, 0.07216878, 0.07216878, 0.07216878,
       0.07216878, 0.07216878, 0.07216878])

In [359]:
z_1=np.sum(D*np.exp(-at_1*y*y_1))

In [360]:
z_1

np.float64(0.8660254037844386)

In [333]:
D

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

In [334]:
D2 = (D * np.exp(-at_1 * y * y_1)) / z_1

In [335]:
D2

array([0.25      , 0.25      , 0.08333333, 0.08333333, 0.08333333,
       0.08333333, 0.08333333, 0.08333333])

In [336]:
math.e**at_1

1.7320508075688774

In [337]:
((D/z_1))

array([0.14433757, 0.14433757, 0.14433757, 0.14433757, 0.14433757,
       0.14433757, 0.14433757, 0.14433757])

In [338]:
D2

array([0.25      , 0.25      , 0.08333333, 0.08333333, 0.08333333,
       0.08333333, 0.08333333, 0.08333333])

In [ ]:
X = data[:,:2]
y = data[:,2]


y_2 = None

b_error,b_stump = float('inf'),None

for j in range(X.shape[1]):
    features = np.sort(np.unique(X[:,j]))

    thresholds = [(features[k]+ features[k+1])/2 for k in range(len(features)-1)]
    # thresholds = [-.75,-.25,0,.25,.75]
    for t in thresholds:
        preds = np.where(X[:,j] >=t,1,-1)

        incorrect = preds !=y

        error = np.sum(D2[incorrect])

        if error > 0.5:
          error = 1 - error
          preds = -preds

        if error < b_error:
            b_error = error
            b_stump = (j, t)
            y_2 = preds

        print(j, t,error)
       

print(b_error, b_stump)


at_2 = (1/2)*math.log((1-b_error)/b_error)
at_2

Feature x1, threshold=-0.75, error=0.4167
Feature x1, threshold=-0.25, error=0.1667
Feature x1, threshold=0.25, error=0.4167
Feature x1, threshold=0.75, error=0.5000
Feature x2, threshold=-0.50, error=0.3333
Feature x2, threshold=0.25, error=0.4167
Feature x2, threshold=0.75, error=0.1667
0.1666666666666664 (0, np.float64(-0.25))


0.8047189562170511

In [342]:
z_2=np.sum(D2*np.exp(-at_2*y*y_2))

In [343]:
z_2

np.float64(0.74535599249993)

In [357]:
X

array([[-1. ,  0. ],
       [-0.5,  0.5],
       [ 0. ,  1. ],
       [ 0.5,  1. ],
       [ 1. ,  0. ],
       [ 1. , -1. ],
       [ 0. , -1. ],
       [ 0. ,  0. ]])

In [356]:
y_2

array([ 1,  1, -1, -1, -1, -1, -1, -1])

In [354]:
y

array([ 1.,  1., -1., -1.,  1.,  1., -1., -1.])

In [362]:
np.sum(D2*np.exp(-at_2*y*y_2))

np.float64(0.74535599249993)

In [365]:
(D2[0] / z_2) * math.e**-at_2

np.float64(0.14999999999999986)

In [363]:
math.e**at_2

2.2360679774997916

In [364]:
math.e**-at_2

0.44721359549995754

In [345]:
D3 = (D2 * np.exp(-at_2 * y * y_2)) / z_2

In [ ]:
X = data[:,:2]
y = data[:,2]


y_3 = None

b_error,b_stump = float('inf'),None

for j in range(X.shape[1]):
    features = np.sort(np.unique(X[:,j]))

    thresholds = [(features[k]+ features[k+1])/2 for k in range(len(features)-1)]
    # thresholds = [-.75,-.25,0,.25,.75]
    for t in thresholds:
        preds = np.where(X[:,j] >=t,1,-1)

        incorrect = preds !=y

        error = np.sum(D3[incorrect])

        if error > 0.5:
          error = 1 - error
          preds = -preds

        if error < b_error:
            b_error = error
            b_stump = (j, t)
            y_3 = preds

        print(j, t,error)
      

print(b_error, b_stump)


at_3 = (1/2)*math.log((1-b_error)/b_error)
at_3

0 -0.75 0.34999999999999964
0 -0.25 0.4999999999999995
0 0.25 0.3499999999999997
0 0.75 0.29999999999999977
1 -0.5 0.4
1 0.25 0.24999999999999978
1 0.75 0.09999999999999987
0.09999999999999987 (1, np.float64(0.75))


1.0986122886681104

In [347]:
y_3

array([ 1,  1, -1, -1,  1,  1,  1,  1])

In [370]:
y

array([ 1.,  1., -1., -1.,  1.,  1., -1., -1.])

In [348]:
D3

array([0.15, 0.15, 0.05, 0.05, 0.25, 0.25, 0.05, 0.05])

In [375]:
np.sum(D3*np.exp(-at_3*y*y_3))

np.float64(0.5999999999999996)

In [376]:
D3*np.exp(-at_3*y*y_3)

array([0.05      , 0.05      , 0.01666667, 0.01666667, 0.08333333,
       0.08333333, 0.15      , 0.15      ])

In [349]:
z_3=np.sum(D3*np.exp(-at_3*y*y_3))
z_3

np.float64(0.5999999999999996)

In [350]:
at_1,at_2,at_3

(0.5493061443340549, 0.8047189562170511, 1.0986122886681104)

In [381]:
y

array([ 1.,  1., -1., -1.,  1.,  1., -1., -1.])

In [382]:
final_preds = np.sign(at_1*y_1 + at_2*y_2 + at_3*y_3)
np.mean(final_preds != y)


np.float64(0.0)

In [352]:
print("h1:", y_1)
print("h2:", y_2)
print("h3:", y_3)
print("final:", final_preds)

h1: [-1 -1 -1 -1  1  1 -1 -1]
h2: [ 1  1 -1 -1 -1 -1 -1 -1]
h3: [ 1  1 -1 -1  1  1  1  1]
final: [ 1.  1. -1. -1.  1.  1. -1. -1.]
