In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

class Perceptron(object):
    def __init__(self):
        """
        Initialize instance of OneHotEncoder for use in onehot function.
        """
        
        self.weights = None     # No need to change. Values for self.weights will be set in the fit function.
        self.classes = None     # No need to change. Values for self.classes will be set in the fit function.
        self.oh = OneHotEncoder()          # TODO Initialize OneHotEncoder

    def onehot(self, Y):
        """
        Helper function to encode the labels into one hot encoding format used in the one-vs-all classifier.
        Replace the class label from 0 and 1 to -1 and 1.

        Args:
                Y: list of class labels

        Return:
                onehotencoded: (N, C) numpy array where:
                                N is the number of datapoints in the list 'Y'
                                C is the number of distinct labels/classes in 'Y'

        Hint:
        1. It may be helpful to refer to sklearn documentation for the OneHotEncoder
        https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
        2. After the normal onehot encoding, replace the 0's with -1's because we will use this for the one-vs-all classifier

        """

        encoded = self.oh.fit_transform(np.array(Y).reshape(-1,1)).toarray()
        encoded[encoded==0]=-1
        return encoded

    def perceptron(self, X, Y, epochs=10):
        """
        1 vs all perceptron algorithm. We will use the regularization term (alpha) as 1.

        Args:
                X: (N, D+1) numpy array of the TF-IDF features for the data.
                Y: (N,) numpy vector of the one-hot encoded labels.
                epochs: Number of epochs for perceptron.

        Return:
                weight: (D+1, 1) weight matrix 

        Hint:
        1. Initialize weight to be 0s
        2. Read the documentation + code of the fit( ) method to understand what needs to be returned by this method.
        3. Note that a bias term has already been added to the dataset in the fit function.
        """
        weights = np.zeros((X.shape[1],1))

        for e in range(10):
                for i in range(X.shape[0]):
                        i_class = (X[i,:]@weights)
                        if i_class * Y[i]<=0:
                                weights = (weights.T + X[i,:]*1*Y[i]).reshape(-1,1)


        


        return weights

    def fit(self, data, labels):
        """
        Fit function for calculating the weights using perceptron.
        NOTE : This function is given and does not have to be implemented or changed.

        Args:
                data: (N, D) TF-IDF features for the data.
                labels: (N, ) list of class labels
        """

        bias_ones = np.ones((len(data), 1))
        X = np.hstack((data, bias_ones))
        Y = self.onehot(labels)

        self.classes = Y.shape[1]
        self.weights = np.zeros((X.shape[1], Y.shape[1]))

        for i in range(Y.shape[1]):
            W = self.perceptron(X, Y[:, i])
            self.weights[:, i] = W[:, 0]

    def predict(self, data):
        """
        Predict function for predicting the class labels.

        Args:
                data: (N, D) TF-IDF features for the data.

        Return:
                predictedLabels: (N,) numpy vector of predicted classes for the data.

        Hint: Remember to address the bias term. It may be helpful to see how the bias term was added in the fit function.
        """

        
        x = np.hstack((data,np.ones((len(data),1))))
        
        return np.argmax( x @ self.weights,axis=1)
    
        
        


In [130]:
X = np.array(
			[[0.37454012, 0.        , 0.73199394, 0.        ],
			[0.        , 0.15599452, 0.05808361, 0.        ],
			[0.60111501, 0.70807258, 0.02058449, 0.        ],
			[0.        , 0.        , 0.        , 0.        ],
			[0.        , 0.        , 0.        , 0.        ],
			[0.61185289, 0.        , 0.29214465, 0.36636184],
			[0.45606998, 0.        , 0.        , 0.        ],
			[0.        , 0.04645041, 0.        , 0.        ],
			[0.        , 0.        , 0.        , 0.80839735],
			[0.        , 0.09767211, 0.        , 0.44015249],
			[0.        , 0.        , 0.03438852, 0.9093204 ],
			[0.25877998, 0.        , 0.31171108, 0.        ],
			[0.        , 0.18485446, 0.96958463, 0.        ],
			[0.        , 0.89482735, 0.59789998, 0.92187424],
			[0.        , 0.        , 0.        , 0.        ]])

input_y = [0, 2, 1, 2, 0, 0, 1, 2, 2, 1, 2, 2, 0, 2, 2]

In [131]:
oh = OneHotEncoder()

encoded = oh.fit_transform(np.array(input_y).reshape(-1,1)).toarray()

In [134]:
test_class = Perceptron()

test_class.fit(X,input_y)

In [135]:
test_class.predict(X)

array([0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2])

In [107]:
test_class.weights

array([[-0.70584564,  2.52898986, -1.16685549],
       [-0.99120168,  1.21933645, -1.28799869],
       [ 2.05108186, -2.70751186, -0.81365063],
       [-0.61863223, -1.06695134,  1.00368981],
       [-1.        , -1.        ,  1.        ]])

In [114]:
X

array([[0.37454012, 0.        , 0.73199394, 0.        ],
       [0.        , 0.15599452, 0.05808361, 0.        ],
       [0.60111501, 0.70807258, 0.02058449, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.61185289, 0.        , 0.29214465, 0.36636184],
       [0.45606998, 0.        , 0.        , 0.        ],
       [0.        , 0.04645041, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.80839735],
       [0.        , 0.09767211, 0.        , 0.44015249],
       [0.        , 0.        , 0.03438852, 0.9093204 ],
       [0.25877998, 0.        , 0.31171108, 0.        ],
       [0.        , 0.18485446, 0.96958463, 0.        ],
       [0.        , 0.89482735, 0.59789998, 0.92187424],
       [0.        , 0.        , 0.        , 0.        ]])

In [116]:
ws = test_class.weights[:,0]
w = ws[:-1]

In [121]:
X[0,:]

array([0.37454012, 0.        , 0.73199394, 0.        ])

In [ ]:
X[0,:]@w + -1


np.float64(0.2370119812568512)

In [115]:
np.zeros((X.shape[0]))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [125]:
predictions = np.zeros((X.shape[0]))
for c in range(test_class.classes):
    ws = test_class.weights[:,c]
    w = ws[:-1]
    bias = ws[-1]
    for i in range(X.shape[0]):
        xi = X[i,:]
        predictions[i]+=xi@w + bias

    

In [126]:
predictions

array([-1.83028365, -1.25072055, -1.38621643, -1.        , -1.        ,
       -1.27774389, -0.70068641, -1.04923111, -1.55124111, -1.40365638,
       -1.6706138 , -1.28840604, -2.62128816, -3.45597669, -1.        ])

In [97]:
x_new = np.hstack((input_x,np.ones((len(input_x), 1))))

In [ ]:
input_x.shape[0]

(15, 4)

In [103]:
test_class.classes

3

In [102]:
test_class.weights[:-1,:]

array([[-0.70584564,  2.52898986, -1.16685549],
       [-0.99120168,  1.21933645, -1.28799869],
       [ 2.05108186, -2.70751186, -0.81365063],
       [-0.61863223, -1.06695134,  1.00368981]])

In [4]:
encoded[encoded==0]=-1

In [37]:
weights = np.zeros((input_x.shape[1],1))
weights.shape

(4, 1)

In [71]:
z=(weights.T + input_x[1,:]*1*encoded[:,0][1]).reshape(-1,1)

In [73]:
weights.shape , z.shape

((4, 1), (4, 1))

In [79]:
Y=encoded[:,0]

In [80]:
weights = np.zeros((input_x.shape[1],1))

for e in range(10):
    for i in range(input_x.shape[0]):
        i_class = (input_x[i,:]@weights)
        if i_class * Y[i]<=0:
            weights = (weights.T + input_x[i,:]*1*Y[i]).reshape(-1,1)

    
    

In [81]:
weights

array([[-0.28143133],
       [-0.8640671 ],
       [ 0.60536618],
       [-0.30269468]])

In [21]:
sum([-0.70584564,  2.52898986, -1.16685549])

0.6562887299999997

In [ ]:
for i in range(input_x.shape[0]):
    for j in range(input_x.shape[1]):
    
        print(input_x[i,j])

0.37454012
0.0
0.73199394
0.0
0.0
0.15599452
0.05808361
0.0
0.60111501
0.70807258
0.02058449
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.61185289
0.0
0.29214465
0.36636184
0.45606998
0.0
0.0
0.0
0.0
0.04645041
0.0
0.0
0.0
0.0
0.0
0.80839735
0.0
0.09767211
0.0
0.44015249
0.0
0.0
0.03438852
0.9093204
0.25877998
0.0
0.31171108
0.0
0.0
0.18485446
0.96958463
0.0
0.0
0.89482735
0.59789998
0.92187424
0.0
0.0
0.0
0.0
