In [135]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

np.random.seed(42)


### SUBMIT THIS FILE TO THE BONUS EXTRA CREDIT GRADESCOPE SECTION ###
def custom_smote(samples: np.ndarray, n: int, k: int) -> np.ndarray:
    """
    Implement the SMOTE algorithm on the training data.
    For this function, you can use scikit-learn's NearestNeighbors function to find
    the k nearest neighbors.

    Hint:
        1. randomly pick a minority sample
        2. find its k nearest neighbors
        3. randomly pick one of the k nearest neighbors and generate a synthetic sample
        4. when k equals 1, the closest neighbor to the current point (not the point itself) is selected
           as the nearest neighbor

    Args:
        samples: (N, D) ndarray of minority class samples
        n: Number of synthetic samples to generate
        k: Number of nearest neighbors
    Return:
        synthetic: (n, D) ndarray of synthetic samples
    """

    knn = NearestNeighbors(n_neighbors=k + 1)
    knn.fit(samples)

    smote_dps = []
    for _ in range(n):
        samples_dp = samples[np.random.randint(samples.shape[0])]
        nearest_indicies = knn.kneighbors([samples_dp])[1][0][1:]
        smote_dp = samples[nearest_indicies[np.random.randint(len(nearest_indicies))]]
        smote_dps.append(samples_dp + np.random.random() * (smote_dp - samples_dp))
    return np.array(smote_dps)


In [136]:
small_sample = np.random.randint(-5, 5, (10,2))

In [138]:
knn = NearestNeighbors(n_neighbors=k+1)
knn.fit(small_sample)

smote_dps = []
for _ in range(4):
    samples_dp = small_sample[np.random.randint(small_sample.shape[0])]
    nearest_indicies = knn.kneighbors([samples_dp])[1][0][1:]
    print(knn.kneighbors([samples_dp]))
    # print(nearest_indicies)
    smote_dp = small_sample[np.random.randint(len(nearest_indicies))]
    smote_dps.append(samples_dp+np.random.random()*(smote_dp-samples_dp))
np.array(smote_dps)

(array([[0.        , 3.60555128, 5.        , 5.09901951, 5.09901951]]), array([[2, 5, 3, 7, 1]]))
(array([[0.        , 1.41421356, 2.        , 5.        , 5.38516481]]), array([[8, 3, 5, 7, 2]]))
(array([[0.        , 1.41421356, 2.        , 2.        , 2.23606798]]), array([[6, 0, 1, 4, 9]]))
(array([[0.        , 0.        , 1.41421356, 2.        , 2.        ]]), array([[1, 4, 0, 7, 6]]))


array([[-1.05693775,  2.45729668],
       [ 0.29970203,  3.71988081],
       [ 1.54950075, -2.54950075],
       [-2.71100878,  0.88440351]])

In [4]:
k=4

In [107]:
smaple_dp_index = np.random.randint(small_sample.shape[0])

In [108]:
sample_datapoint = small_sample[smaple_dp_index]

In [109]:
knn = NearestNeighbors(n_neighbors=1)

In [110]:
knn.fit(small_sample)

NearestNeighbors(n_neighbors=1)

In [112]:
sample_datapoint

array([-5,  4])

In [115]:
nearest_indicies = knn.kneighbors([sample_datapoint])[1]

In [116]:
smote_dp=small_sample[np.random.randint(nearest_indicies.shape[1])]

In [117]:
smote_dp

array([-3,  0])

In [119]:
np.linspace(sample_datapoint,smote_dp,2)

array([[-5.,  4.],
       [-3.,  0.]])

In [85]:
np.full((3,2),smote_dp)

array([[-3,  1],
       [-3,  1],
       [-3,  1]])